### PR TITLE
Solve the 403 error at a specific URL.

### PR DESCRIPTION
**Pull request by JaeseokWoo**
Hello
I used "react-link-preview" for my project and confirmed that a 403 error appeared at a specific URL.
For example, https://www.coupang.com/.
This site seems to be using AkamaiGhost server and returns 403.

In order to solve it, I found that Accept-Encoding should be added to the header.
To add Accept-Encodingd, I upgraded the html-metadata-parser version.

I tested it on my local and confirmed that it was solved.
But I didn't know why it was solved.
I want to help with the "react-link-preview" and want feedback.

I am currently a student, and I am not good at English.
That's why the above content is a translator.

### CODE REVIEW

**Comment by Dhaiwat10** [comment]
Hey, thanks for the pull request. I would accept this instantly but since we are introducing a major / breaking change in the `html-metadata-parser` dependency, we need to make sure that nothing breaks. Since I have not written any tests for this, I need to test it thoroughly 😅 

I will get back to you

**Comment by JaeseokWoo** [comment]
Thank you for replying.
I think it's good to test thoroughly and then apply it.
If I have a chance, I want to contribute.
Thank you.😄

**Comment by Dhaiwat10** [comment]
@JaeseokWoo I tried this out locally and I found a breaking change straight away. If you try to get metadata for https://www.youtube.com/watch?v=5dFa4ijgIPI for example, the old code will give you a proper result but the new one will return undefined and placeholders.

**Comment by Dhaiwat10** [comment]
Can you look into why this may be happening? I would love to accept this PR but I also want to make sure none of the existing functionality is broken.

**Comment by JaeseokWoo** [comment]
Are you talking about undefined/img-placeholder.jpg?
I found the cause of this.
The cause is `url.toLowerCase()`.
I worked on the no-redis-caching branch, and the v2 logic of the master branch and the no-redis-caching branch is a little different.
I removed `url.toLowerCase()` and tested it, and it seems to be working well.
Please check.😄

**Comment by JaeseokWoo** [comment]
https://github.com/Dhaiwat10/rlp-proxy/pull/8#issue-1003988141

I just checked and the html-metadata-parser version of master branch is 2.0.2.

**Comment by Dhaiwat10** [comment]
@JaeseokWoo please feel free to create a new branch and PR off of the master branch!

**Comment by Dhaiwat10** [comment]
Closing in favor of #12

**Pull request closed without merging**
